### PR TITLE
Fix Menu -> Repository activity and cleanup layouts on content_main

### PR DESCRIPTION
**Pull request by Iscle**
The repository activity works now. The problem was that Android P has new network policies and we didn't account for it.

### CODE REVIEW

**Comment by meefik** [comment]
It works in Android 9 and not working in Android 4..

**Comment by Iscle** [comment]
Oh man, when we fix it in one version it breaks the other one hahaha let me check again!

**Comment by Iscle** [comment]
> It works in Android 9 but not working in Android 4..

Can you specify the version? It crashed once on API 19 but it works after the second attempt. I couldn't catch the logcat.

**Comment by meefik** [comment]
My Android 4.4.2

**Comment by Iscle** [comment]
> My Android 4.4.2

`02-23 21:03:21.146 2084-2123/? W/System.err: java.io.FileNotFoundException: env
02-23 21:03:21.146 2084-2123/? W/System.err:     at android.content.res.AssetManager.openAsset(Native Method)
02-23 21:03:21.146 2084-2123/? W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:316)
02-23 21:03:21.146 2084-2123/? W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:290)
02-23 21:03:21.146 2084-2123/? W/System.err:     at ru.meefik.linuxdeploy.EnvUtils.extractFile(EnvUtils.java:53)
02-23 21:03:21.146 2084-2123/? W/System.err:     at ru.meefik.linuxdeploy.EnvUtils.extractDir(EnvUtils.java:87)
02-23 21:03:21.156 2084-2123/? W/System.err:     at ru.meefik.linuxdeploy.EnvUtils.updateEnv(EnvUtils.java:318)
02-23 21:03:21.156 2084-2123/? W/System.err:     at ru.meefik.linuxdeploy.UpdateEnvTask.doInBackground(UpdateEnvTask.java:32)
02-23 21:03:21.156 2084-2084/? D/EGL_emulation: eglMakeCurrent: 0xb9829110: ver 2 0
02-23 21:03:21.156 2084-2123/? W/System.err:     at ru.meefik.linuxdeploy.UpdateEnvTask.doInBackground(UpdateEnvTask.java:10)
02-23 21:03:21.156 2084-2123/? W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
02-23 21:03:21.156 2084-2123/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-23 21:03:21.156 2084-2123/? W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
02-23 21:03:21.156 2084-2123/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-23 21:03:21.156 2084-2123/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-23 21:03:21.166 2084-2123/? W/System.err:     at java.lang.Thread.run(Thread.java:841)`

The repository menu does work for me, however what doesn't work is everything else. It looks like the env folder is not being found. Should this folder be copied automatically when installing the app or later when it's opened?

**Comment by meefik** [comment]
After opened

https://github.com/meefik/linuxdeploy/blob/3f6ba4400b732396a5e92e0a6636c68f11384ede/app/src/main/java/ru/meefik/linuxdeploy/MainActivity.java#L101

**Comment by Iscle** [comment]
This is very strange, I don't see why it doesn't work now if it was working before... On Pie the same error is thrown... But it shouldn't be too difficult to solve.

Do you mind waiting a few hours until I have time to solve it?

**Comment by meefik** [comment]
> Do you mind waiting a few hours until I have time to solve it?

Yes, of course :)

**Comment by Iscle** [comment]
I think it's a git issue. The submodule pointing to linuxdeploy-cli is not downloading here:

https://github.com/meefik/linuxdeploy/tree/master/app/src/main/assets

Maybe you will need to re-create it.

**Pull request merged**
