### PR TITLE
Help text updated.

### PR DESCRIPTION
**Pull request by cloud9350**
link wiki

### CODE REVIEW

**Comment by niraj281984** [comment]
Hey,i m not accesing internet in kali.....how i fix it...plese help me

**Comment by cloud9350** [comment]
@niraj281984 Try another gnu linux

**Comment by junaid2211** [comment]
pls anybody help.my installation is stopping at
"configuring graphics/vnc
>>>deploy"

**Comment by junaid2211** [comment]
what to do meefik pls reply fast

**Comment by cloud9350** [comment]
@junaid2211 You must paste log here.
settings -> debug -> enable track / log

**Comment by junaid2211** [comment]
thnx for reply the problem is solved i was trying to run linux deploy with kali armhf image...
at last i downloaded kali basic ext4 and itt worked like charm

**Comment by junaid2211** [comment]
i want to know how to upgrade my kali linux to 2.0

**Comment by cloud9350** [comment]
@junaid2211 Upgrade your phone OS (Kernel)

**Comment by jdoggnaylor56** [comment]
I have the bases of the program I'm trying to download and receive dade feed from the URL

**Pull request merged**
