### PR TITLE
Fixed printf in EnvUtils.java

### PR DESCRIPTION
**Pull request by DeicPro**
To use built-in busybox applet

### CODE REVIEW

**Comment by meefik** [comment]
Why is this? printf built-in command in ash and not used external programs.

**Comment by DeicPro** [comment]
Because if you have not got busybox or have got but not installed (applets symlinked), printf is not found when is run from there (obviously, printf not exist in any dir defined in PATH). I will attach a image in a while.

**Comment by DeicPro** [comment]
Status debug w/o Busybox installed
screenshot_2016-10-21-09-47-38-569_ru meefik linuxdeploy

Status w/o Busybox installed
screenshot_2016-10-21-09-47-52-628_ru meefik linuxdeploy

Status with Busybox installed
screenshot_2016-10-21-09-49-35-641_ru meefik linuxdeploy

**Comment by meefik** [comment]
Fixed in the next version.

**Pull request closed without merging**
