### PR TITLE
Fix issue #367

### PR DESCRIPTION
**Pull request by cloud9350**
Change exec permission mod
https://github.com/meefik/linuxdeploy/issues/357

### CODE REVIEW

**Comment by cloud9350** [comment]
This is the mount does not resolve the error.

**Comment by cloud9350** [comment]
This mount fix is temporary.
I'm working.
Tested on CyanogenMod11

**Comment by meefik** [comment]
Please, try LD version 1.5.5-187
https://github.com/meefik/linuxdeploy/releases/tag/1.5.5

**Comment by cloud9350** [comment]
@meefik /sys/fs/selinux mount is fixed. (Now working).
Permission problem is fixed.
mount problem is fixed.

**Pull request closed without merging**
